"""initial_schema_9_tables

Revision ID: 7f265dd2fccc
Revises: 
Create Date: 2026-08-28 00:22:57.214957

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7f265dd2fccc"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_role"), ["role"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notifications_read_at"), ["read_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_notifications_type"), ["type"], unique=False)
        batch_op.create_index(batch_op.f("ix_notifications_user_id"), ["user_id"], unique=False)

    op.create_table(
        "patients",
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("caregiver_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("dob", sa.String(length=50), nullable=True),
        sa.Column("medical_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["caregiver_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("patients", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_patients_caregiver_id"), ["caregiver_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_patients_user_id"), ["user_id"], unique=False)

    op.create_table(
        "activity_logs",
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("action_type", sa.String(length=100), nullable=False),
        sa.Column(
            "detail",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("activity_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_activity_logs_action_type"), ["action_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activity_logs_patient_id"), ["patient_id"], unique=False
        )

    op.create_table(
        "emergency_events",
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("trigger_method", sa.String(length=50), nullable=False),
        sa.Column("contacts_notified", sa.Integer(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("emergency_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_emergency_events_patient_id"), ["patient_id"], unique=False
        )

    op.create_table(
        "family_members",
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("relationship", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("family_members", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_family_members_patient_id"), ["patient_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_family_members_user_id"), ["user_id"], unique=False)

    op.create_table(
        "reminders",
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recurrence", sa.String(length=50), nullable=True),
        sa.Column("priority", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reminders_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_reminders_created_by"), ["created_by"], unique=False)
        batch_op.create_index(batch_op.f("ix_reminders_patient_id"), ["patient_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_reminders_scheduled_at"), ["scheduled_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_reminders_status"), ["status"], unique=False)

    op.create_table(
        "face_embeddings",
        sa.Column("family_member_id", sa.String(length=36), nullable=False),
        sa.Column(
            "embedding",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("photo_url", sa.String(length=1024), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_member_id"],
            ["family_members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("face_embeddings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_face_embeddings_family_member_id"), ["family_member_id"], unique=False
        )

    op.create_table(
        "recognitions",
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("matched_member_id", sa.String(length=36), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("is_unknown", sa.Boolean(), nullable=False),
        sa.Column("image_url", sa.String(length=1024), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["matched_member_id"],
            ["family_members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recognitions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recognitions_matched_member_id"), ["matched_member_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recognitions_patient_id"), ["patient_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recognitions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recognitions_patient_id"))
        batch_op.drop_index(batch_op.f("ix_recognitions_matched_member_id"))

    op.drop_table("recognitions")
    with op.batch_alter_table("face_embeddings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_face_embeddings_family_member_id"))

    op.drop_table("face_embeddings")
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reminders_status"))
        batch_op.drop_index(batch_op.f("ix_reminders_scheduled_at"))
        batch_op.drop_index(batch_op.f("ix_reminders_patient_id"))
        batch_op.drop_index(batch_op.f("ix_reminders_created_by"))
        batch_op.drop_index(batch_op.f("ix_reminders_category"))

    op.drop_table("reminders")
    with op.batch_alter_table("family_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_family_members_user_id"))
        batch_op.drop_index(batch_op.f("ix_family_members_patient_id"))

    op.drop_table("family_members")
    with op.batch_alter_table("emergency_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_emergency_events_patient_id"))

    op.drop_table("emergency_events")
    with op.batch_alter_table("activity_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activity_logs_patient_id"))
        batch_op.drop_index(batch_op.f("ix_activity_logs_action_type"))

    op.drop_table("activity_logs")
    with op.batch_alter_table("patients", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_patients_user_id"))
        batch_op.drop_index(batch_op.f("ix_patients_caregiver_id"))

    op.drop_table("patients")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_user_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_type"))
        batch_op.drop_index(batch_op.f("ix_notifications_read_at"))

    op.drop_table("notifications")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_role"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
